# Generated by Django 5.2.6 on 2026-02-21 23:48

# dev-v0.1.0 - add subtitle timing offset

#####
# CHANGELOG
# v0.1.0 - Initial commit
#####

# Stored at /mediacms/files/migrations/0015_add_subtitle_timing_offset.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='subtitle_timing_offset',
            field=models.FloatField(default=0.0, help_text='Subtitle timing offset in seconds (negative = delay subtitles, positive = advance subtitles)'),
        ),
    ]